### ISSUE TITLE
Classes in single level namespace not resovled correctly for PHP 8

### ISSUE THREAD

**Issue by abenettt** [ergebnis/classy#326]
#### Steps required to reproduce the problem

1. Run PHP 8
2. Have class with single level namespace such as `App`
3. Try to resolve using ```Constructs::fromDirectory($directory)```
4. Check `Construct` `name`

Example Repo is under: https://github.com/abenettt/classy-namespace-error
#### Expected Result

* FQCN to be resolved correctly and tests to pass

#### Actual Result

* FQCN is resolved as name of the file so the test fails

**Comment by localheinz** [comment]
Thank you for reporting, @abenettt!

Will take a look!

**Comment by localheinz** [comment]
@abenettt 

Released as https://github.com/ergebnis/classy/releases/tag/1.1.1!
